# Generated by Django 5.1.4 on 2025-01-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='encargado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
