# Generated by Django 5.1.4 on 2025-01-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='encargado',
            field=models.CharField(blank=True, default='Sin encargado', max_length=200),
        ),
    ]
